version: '2'  

# remove port bind, virtual host and front-proxy net for production

services:  
  db:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - VIRTUAL_HOST=${MYSQL_HOST}
    networks:
      - piwik-net

  pwapp:
    image: piwik
    volumes:
      - app-config:/var/www/html/config
    depends_on:
      - db
    networks:
      - piwik-net

  web:
    build: nginx 
    volumes:
      - web-certs:/etc/ssl/private/
    expose:
      - "80"
      - "443"
    volumes_from:
      - pwapp
    environment:
      - VIRTUAL_HOST=${PIWIK_HOST}
    depends_on:
      - pwapp
    networks:
      - piwik-net

  example:
    build: ./example
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${CLIENT_HOST}
    networks:
      - piwik-net

networks:
  piwik-net:

volumes:
  db-data:
  app-config:
  web-certs:
